// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var extractMeowed, getHelpText, getOptions, log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("cliargumentsmodule"));

import meow from 'meow';

import process from "node:process";

//#############################################################
//region internal functions
getHelpText = function() {
  log("getHelpText");
  return `Usage
    $ 
    
Options
    optional:
        arg1, --root <root-directory>, -r <root-directory>
            define the root directory of your project in which to run the devloop


Examples
    $ devloop  ~/projects/my-mega-project
    $ devloop  -r ~/projects/my-mega-project
    $ devloop  -root ~/projects/my-mega-project`;
};

getOptions = function() {
  log("getOptions");
  return {
    importMeta: import.meta,
    flags: {
      root: { //optionsname
        type: "string", // or string
        alias: "r"
      }
    }
  };
};

//#############################################################
extractMeowed = function(meowed) {
  var wd;
  log("extractMeowed");
  wd = process.cwd(); // default
  if (meowed.input[0]) {
    wd = meowed.input[0];
  }
  if (meowed.flags.root) {
    wd = meowed.flags.root;
  }
  return {wd};
};

//endregion

//#############################################################
export var extractArguments = function() {
  var extract, meowed;
  log("extractArguments");
  meowed = meow(getHelpText(), getOptions());
  extract = extractMeowed(meowed);
  return extract;
};
