// Generated by CoffeeScript 2.7.0
//#############################################################################
var err, localConfig;

import * as utils from "./configutils.js";

//#############################################################################
localConfig = {};

try {
  localConfig = (await utils.readLocalConfig());
} catch (error) {
  err = error;
  console.error(err);
}

//#############################################################################
export var tgToken = localConfig.tgToken || "";

export var tgChatId = localConfig.chatId || "";

//#############################################################################
export var maxCycles = 10;

//#############################################################################
export var appName = "devloop";

export var appVersion = "0.0.1";

//#############################################################################
//# TODO implement mechanics for updating the config -> calling utils.updateLocalConfig(content)
//# TODO implement listeners such that other modules also receive the updates
