// Generated by CoffeeScript 2.7.0
//#############################################################################
var err, localConfig, onChangeListeners;

import * as utils from "./configutils.js";

onChangeListeners = {};

//#############################################################################
localConfig = {};

try {
  localConfig = (await utils.readLocalConfig());
} catch (error) {
  err = error;
  console.error(err);
}

//#############################################################################
export var onChange = function(prop, cb) {
  if (onChangeListeners[prop] == null) {
    onChangeListeners[prop] = [];
  }
  onChangeListeners[prop].push(cb);
};

export var updateConfig = async function(content) {
  var callbacks, cb, i, j, len, len1, prop, updated;
  updated = (await utils.updateLocalConfig(content, localConfigProps));
  for (i = 0, len = updated.length; i < len; i++) {
    prop = updated[i];
    if (!(onChangeListeners[prop] != null)) {
      continue;
    }
    callbacks = onChangeListeners[prop];
    for (j = 0, len1 = callbacks.length; j < len1; j++) {
      cb = callbacks[j];
      cb(content[prop]);
    }
  }
};

//#############################################################################
// possible localConfig Props
//#############################################################################
export var tgToken = localConfig.tgToken || "";

export var tgChatId = localConfig.tgChatId || "";

export var maxCycles = localConfig.maxCycles || 10;

//#############################################################################
// Should contain all possible localConfig Props
export var localConfigProps = ["tgToken", "tgChatId", "maxCycles"];

//#############################################################################
// static cli config
//#############################################################################
export var appName = "devloop";

export var appVersion = "0.0.1";
