#!/usr/bin/env node
// Generated by CoffeeScript 2.7.0
var run;

import Modules from "./allmodules.js";

//###########################################################
global.allModules = Modules;

import * as cfg from "./configmodule.js";

//###########################################################
run = async function() {
  var err, m, n, promises;
  try {
    promises = (function() {
      var results;
      results = [];
      for (n in Modules) {
        m = Modules[n];
        if (m.initialize != null) {
          results.push(m.initialize(cfg));
        }
      }
      return results;
    })();
    await Promise.all(promises);
    return (await Modules.startupmodule.cliStartup());
  } catch (error) {
    err = error;
    return console.error(err);
  }
};

//###########################################################
run();
