// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("mainprocessmodule"));

//endregion

//#############################################################################
export var initialize = function(cfg) {
  log("initialize");
};

//#############################################################################
export var execute = function(args) {
  log("execute");
};

// TODO implement
