// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var log, olog, outerCycleActions, setState, userDecisionCycle;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("mainprocessmodule"));

import * as Stt from "./statemodule.js";

import * as ui from "./uimodule.js";

import * as taskLoop from "./taskloopmodule.js";

import * as uConf from "./userconfigurationmodule.js";

//#############################################################################
outerCycleActions = {
  "start task execution": function() {
    return taskLoop.execute();
  },
  "configure": function() {
    return uConf.configure();
  },
  "die!": function() {
    return process.exit(0);
  }
};


//#############################################################################
export var execute = async function() {
  var err, state;
  log("execute");
  state = (await Stt.readState());
  try {
    while (true) {
      //# TODO: figure out how to apply state
      await userDecisionCycle();
    }
  } catch (error) {
    err = error;
    console.log(err);
  }
};

//#############################################################################
userDecisionCycle = async function() {
  var choice, uiChoices;
  log("outerCycle");
  uiChoices = Object.keys(outerCycleActions);
  choice = (await ui.retrieveChoice("Welcome to the Devloop!", uiChoices));
  return (await outerCycleActions[choice]());
};

//#############################################################################
setState = async function(taskId, stateString) {
  log("setState");
  state["latest-taskId"] = taskId;
  state["latest-state"] = stateString;
  await Stt.writeState();
};
