// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var log, olog, outerCycleActions, userDecisionCycle;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("mainprocessmodule"));

import * as Stt from "./statemodule.js";

import * as ui from "./uimodule.js";

import * as taskLoop from "./taskloopmodule.js";

import * as uConf from "./userconfigurationmodule.js";

//#############################################################################
outerCycleActions = {
  "run devloop": function() {
    return taskLoop.execute();
  },
  "configure": function() {
    return uConf.configure();
  },
  "die!": function() {
    return process.exit(0);
  }
};


//#############################################################################
export var execute = async function() {
  var err;
  log("execute");
  await Stt.readState();
  try {
    while (true) {
      await userDecisionCycle();
    }
  } catch (error) {
    err = error;
    return;
  }
};

//#############################################################################
userDecisionCycle = async function() {
  var choice, uiChoices;
  log("outerCycle");
  uiChoices = Object.keys(outerCycleActions);
  choice = (await ui.retrieveChoice("Welcome to the Devloop!", uiChoices));
  return (await outerCycleActions[choice]());
};
