// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var baseDir, configPath, log, olog, stateFileName, stateFilePath;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("pathmodule"));

import path from "node:path";

import * as Stt from "./statemodule.js";

//###########################################################
// Manage all application paths
// keeps all paths and sets it correctly for the specific modules

//###########################################################
stateFileName = "devloopState.json"; // default stateFileName


//###########################################################
baseDir = "";

configPath = "";

stateFilePath = "";

//###########################################################
export var initialize = function(cfg) {
  log("initialize");
  // fileName might be configured
  if (cfg.stateFileName != null) {
    stateFileName = cfg.stateFileName;
  }
};

//###########################################################
export var setWorkingDirectory = function(wd) {
  log("setWorkingDirectory");
  if (wd == null) {
    throw new Error("No Working directory!");
  }
  //# StateFile
  stateFilePath = path.resolve(wd, stateFileName);
  Stt.setStateFilePath(stateFilePath);
  log(stateFilePath);
};
