// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("startupmodule"));

import * as mp from "./mainprocessmodule.js";

import * as ca from "./cliargumentsmodule.js";

import * as pth from "./pathmodule.js";

//endregion

//#############################################################################
export var cliStartup = async function() {
  var e, err;
  log("cliStartup");
  try {
    e = ca.extractArguments();
    pth.setWorkingDirectory(e.wd);
    await mp.execute(e);
    log("gracefully terminated!");
  } catch (error) {
    err = error;
    console.error(err);
    process.exit(-1);
  }
};
