// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var defaultState, log, olog, state, stateFilePath;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("statemodule"));

import fs from "node:fs/promises";

//###########################################################
state = null;

stateFilePath = "";

//###########################################################
defaultState = {
  "latest-taskId": 0,
  "latest-state": ""
};

//###########################################################
export var setStateFilePath = function(path) {
  return stateFilePath = path;
};

//###########################################################
export var getState = function() {
  return state;
};

//###########################################################
export var readState = async function() {
  var content, err;
  log("readState");
  try {
    content = (await fs.readFile(stateFilePath, "utf8"));
    state = JSON.parse(content);
  } catch (error) {
    err = error;
    if (err.code !== "ENOENT") {
      throw err;
    }
  }
  olog(state);
  if (state != null) {
    return state;
  }
  state = defaultState;
  await writeState();
};

export var writeState = async function() {
  var content;
  log("writeState");
  content = JSON.stringify(state, null, 4);
  await fs.writeFile(stateFilePath, content, "utf8");
};
