// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var defaultState, fileName, log, olog, state, stateFilePath;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("statemodule"));

import fs from "node:fs/promises";

import path from "node:path";

//###########################################################
fileName = "devloopState.json"; // default fileName

stateFilePath = "";

state = null;

//###########################################################
defaultState = {
  "latest-taskId": 0,
  "latest-state": ""
};

//###########################################################
export var initialize = function(cfg) {
  log("initialize");
  // fileName might be configured
  if (cfg.fileName != null) {
    fileName = cfg.fileName;
  }
};

//###########################################################
export var readState = async function(wd) {
  var content, err;
  log("readState");
  if (wd == null) {
    throw new Error("No Working directory!");
  }
  stateFilePath = path.resolve(wd, fileName);
  log(stateFilePath);
  try {
    content = (await fs.readFile(stateFilePath, "utf8"));
    state = JSON.parse(content);
  } catch (error) {
    err = error;
    if (err.code !== "ENOENT") {
      throw err;
    }
  }
  olog(state);
  if (state != null) {
    return state;
  }
  state = defaultState;
  await writeState();
  return state;
};

//###########################################################
export var writeState = async function() {
  var content;
  log("writeState");
  content = JSON.stringify(state, null, 4);
  await fs.writeFile(stateFilePath, content, "utf8");
};
