// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var action, iteration, log, logState, maxCycles, olog, setState, state, stopExecution, taskExecutionCycle;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("taskloopmodule"));

import * as Stt from "./statemodule.js";

//#############################################################################
state = null;

iteration = 0;

action = null;

//#############################################################################
maxCycles = 2e308;


//#############################################################################
export var initialize = function(cfg) {
  log("initialize");
  if (cfg.maxCycles != null) {
    maxCycles = cfg.maxCycles;
  }
};

//#############################################################################
export var execute = async function() {
  var err;
  log("execute");
  process.on("SIGINT", stopExecution);
  try {
    while (true) {
      await taskExecutionCycle();
    }
  } catch (error) {
    err = error;
    console.log(err);
  }
};

//#############################################################################
stopExecution = function() {
  log("stopExecution - SIGINT received");
  //# TODO graceful shutdown
  return process.exit(0);
};

//#############################################################################
taskExecutionCycle = function() {
  logState();
  if (iteration === maxCycles) {
    throw new Error("Exceeded maxCycles!");
  }
  //# TODO implement
  iteration++;
};

//#############################################################################
logState = function() {
  return log(`@${new Date()}:${iteration} ${state["latest-state"]} TaskId:${state["latest-taskId"]} action: ${action} `);
};

//#############################################################################
setState = async function(taskId, stateString) {
  log("setState");
  state["latest-taskId"] = taskId;
  state["latest-state"] = stateString;
  await Stt.writeState();
};
