// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var action, applyLatestState, checkCycleLimit, claudeAbortion, iteration, log, logState, maxCycles, olog, processError, run, runClaude, setState, state, stopExecution, taskExecutionCycle, updateMaxCycles;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("taskloopmodule"));

import * as Stt from "./statemodule.js";

import * as tg from "./tgmodule.js";

//#############################################################################
state = null;

iteration = 0;

action = null;

//#############################################################################
maxCycles = -1; // is taken as infinite

//#############################################################################
claudeAbortion = null;

//#############################################################################
run = false;

//#############################################################################

//#############################################################################
export var initialize = function(cfg) {
  log("initialize");
  if (cfg.maxCycles != null) {
    maxCycles = cfg.maxCycles;
  }
  cfg.onChange("maxCylces", updateMaxCycles);
  process.on("SIGINT", stopExecution);
};

//#############################################################################
updateMaxCycles = function(newVal) {
  return maxCycles = newVal;
};

//#############################################################################
export var execute = async function() {
  var err;
  log("execute");
  applyLatestState();
  iteration = 0;
  run = true;
  tg.send("Started Devloop - now tasks are executed autonomously.\n");
  while (run) {
    try {
      await taskExecutionCycle();
    } catch (error) {
      err = error;
      processError(err);
    }
  }
};

//#############################################################################
applyLatestState = function() {
  var stateString;
  log("applyLatestState");
  state = Stt.getState();
  stateString = state["latest-state"];
  //# TODO check if state is applicable
  //# TODO handle broken state (e.g. if last task execution might still be running)
  switch (stateString) {
    case "":
      return;
    default:
      console.error(`We don't know how to apply State: ${stateString}`);
  }
};

//#############################################################################
checkCycleLimit = function() {
  if (!(maxCycles > 0)) { // infinite
    return;
  }
  if (iteration >= maxCycles) {
    throw new Error("Exceeded maxCycles!");
  }
};

//#############################################################################
processError = function(err) {
  log("processError");
  log(err);
  //# TODO decide which errors should result in switching off the execution cycle
  run = false; // For now: switch if off on every error
};


//#############################################################################
stopExecution = function() {
  log("stopExecution - SIGINT received");
  run = false;
  if (claudeAbortion != null) {
    claudeAbortion();
  }
};

//#############################################################################
runClaude = async function() {
  var fakeClaudProcess;
  log("runClaude");
  //# TODO implement
  fakeClaudProcess = function(rslv, rjct) { // mocked claude Process with simple delay
    setTimeout(rslv, 33333);
    claudeAbortion = rjct;
  };
  await new Promise(fakeClaudProcess);
};

//#############################################################################
taskExecutionCycle = async function() {
  checkCycleLimit();
  logState();
  //# TODO implement
  await runClaude();
  //# Save new State.
  iteration++;
};

//#############################################################################
logState = function() {
  return console.log(`@${(new Date()).toISOString()}:${iteration} ${state["latest-state"]} TaskId:${state["latest-taskId"]} action: ${action} `);
};

//#############################################################################
setState = async function(taskId, stateString) {
  log("setState");
  state["latest-taskId"] = taskId;
  state["latest-state"] = stateString;
  await Stt.writeState();
};
