// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var chatId, log, olog, tgUrlSendMessage, updateChatId, updateToken;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("tgmodule"));

//endregion

//###########################################################
//region Local Variables
tgUrlSendMessage = null;

chatId = null;

//endregion

//###########################################################
export var initialize = function(cfg) {
  log("initialize");
  cfg.onChange("tgChatId", updateChatId);
  chatId = cfg.tgChatId;
  cfg.onChange("tgChatId", updateChatId);
  tgUrlSendMessage = 'https://api.telegram.org/bot' + cfg.tgToken + '/sendMessage';
  cfg.onChange("tgToken", updateToken);
};

//###########################################################
updateChatId = function(newVal) {
  return chatId = newVal;
};

updateToken = function(newVal) {
  return tgUrlSendMessage = 'https://api.telegram.org/bot' + newVal + '/sendMessage';
};

//###########################################################
export var send = async function(msg) {
  var err, options, resp;
  options = {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: '{"chat_id":' + chatId + ',"text":"' + msg + '"}'
  };
  try {
    resp = (await fetch(tgUrlSendMessage, options));
  } catch (error) {
    err = error;
    console.error(err);
  }
  if (!resp.ok) {
    console.error(`Telegram Response was not OK! (${resp.status})`);
  }
};
