// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("uimodule"));

import enquirer from "enquirer";

//###########################################################
export var initialize = function() {
  log("initialize");
};

//###########################################################
//region Main Interface
//# let's see if we need to initialize anything here
export var retrieveString = async function(prompt) {
  var err, response;
  log("retrieveString");
  try {
    response = (await enquirer.prompt({
      type: "input",
      name: "value",
      message: prompt
    }));
    log("received response");
    olog(response);
    return response.value;
  } catch (error) {
    err = error;
    log(err);
  }
  console.log("User input rejected - Bye!");
  process.exit(0);
};

//###########################################################
export var retrieveSecret = async function(prompt) {
  var err, response;
  log("retrieveSecret");
  try {
    response = (await enquirer.prompt({
      type: "password",
      name: "value",
      message: prompt
    }));
    log("received response");
    olog(response);
    return response.value;
  } catch (error) {
    err = error;
    log(err);
  }
  console.log("User input rejected - Bye!");
  process.exit(0);
};

//###########################################################
export var retrieveChoice = async function(prompt, choices) {
  var err, response;
  log("retrieveChoice");
  try {
    response = (await enquirer.prompt({
      type: "select",
      name: "value",
      message: prompt,
      choices: choices
    }));
    return response.value;
  } catch (error) {
    err = error;
    log(err);
  }
  console.log("User input rejected - Bye!");
  process.exit(0);
};

//endregion
