// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var configurationOptions, effectiveMaxCycles, localMaxCycles, localTgChatId, localTgToken, log, olog, printConfig, setChatId, setMaxCycles, setTelegramToken;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("userconfigurationmodule"));

import * as ui from "./uimodule.js";

import * as cfg from "./configmodule.js";

//###########################################################
configurationOptions = {
  "set telegram-bot token": async function() {
    return (await setTelegramToken());
  },
  "set chat id": async function() {
    return (await setChatId());
  },
  "set max cycles": async function() {
    return (await setMaxCycles());
  },
  "check config": function() {
    return printConfig();
  },
  "back": function() {} // handled in loop
};

//###########################################################
// handle values locally - for updates
localTgToken = cfg.tgToken;

localTgChatId = cfg.tgChatId;

localMaxCycles = cfg.maxCycles;

//###########################################################
export var configure = async function() {
  var choice, choices, err;
  log("configure");
  choices = Object.keys(configurationOptions);
  while (true) {
    try {
      choice = (await ui.retrieveChoice("Configuration:", choices));
    } catch (error) {
      err = error;
      return;
    }
    if (choice === "back") {
      return;
    }
    await configurationOptions[choice]();
  }
};

//###########################################################
effectiveMaxCycles = function() {
  if (localMaxCycles < 1) {
    return "Infinite";
  }
  return localMaxCycles;
};

//###########################################################
printConfig = function() {
  log("printConfig");
  console.log("_________________________________ currently configured:");
  console.log("");
  console.log(`tgToken:    ${localTgToken || '(not set)'}`);
  console.log(`tgChatId:   ${localTgChatId || '(not set)'}`);
  console.log(`maxCycles:  ${effectiveMaxCycles()}`);
  console.log("");
};

//###########################################################
setTelegramToken = async function() {
  var err, token;
  log("setTelegramToken");
  try {
    token = (await ui.retrieveSecret("Telegram Bot Token:"));
  } catch (error) {
    err = error;
    return;
  }
  await cfg.updateConfig({
    tgToken: token
  });
  localTgToken = token;
  console.log("Token updated.");
};

setChatId = async function() {
  var chatId, err;
  log("setChatId");
  try {
    chatId = (await ui.retrieveString("Telegram Chat ID:"));
  } catch (error) {
    err = error;
    return;
  }
  await cfg.updateConfig({
    tgChatId: chatId
  });
  localTgChatId = chatId;
  console.log("Chat ID updated.");
};

setMaxCycles = async function() {
  var err, input, num;
  log("setMaxCycles");
  try {
    input = (await ui.retrieveString(`Max Cycles (current: ${effectiveMaxCycles()}):`));
  } catch (error) {
    err = error;
    return;
  }
  num = parseInt(input, 10);
  if (!input || num < 1) {
    num = -1; // interpreted as Infinite
  }
  if (input && isNaN(num)) {
    console.log('Invalid input.\n  Please enter a positive number for setting a finite maximum ot task cylces.\n  Notice: 0, negative numbers and empty input leads to "Infinite".');
    return;
  }
  await cfg.updateConfig({
    maxCycles: num
  });
  localMaxCycles = num;
  console.log("Max cycles updated.");
};
