// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var configurationOptions, log, olog, printConfig, setChatId, setTelegramToken, terminateConfiguration;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("userconfigurationmodule"));

import * as ui from "./uimodule.js";

//###########################################################
configurationOptions = {
  "set telegram-bot token": async function() {
    return (await setTelegramToken());
  },
  "set chat id": async function() {
    return (await setChatId());
  },
  "check config": function() {
    return printConfig();
  },
  "back": function() {
    return terminateConfiguration();
  }
};

//###########################################################
export var configure = function() {
  log("configure");
};

//###########################################################
//# TODO start loop to Ask for user Choices
terminateConfiguration = function() {
  log("terminateConfiguration");
};

//# TODO implement
printConfig = function() {
  log("printConfig");
};

//# TODO implement only print what we maintain here (tgToken + tgChatId)
setTelegramToken = function() {
  log("setTelegramToken");
};

//# TODO implement
setChatId = function() {
  log("setChatId");
};

//# TODO implement
