// Generated by CoffeeScript 2.7.0
//###########################################################
//region debug
var configurationOptions, done, localMaxCycles, localTgChatId, localTgToken, log, olog, printConfig, setChatId, setMaxCycles, setTelegramToken;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("userconfigurationmodule"));

import * as ui from "./uimodule.js";

import * as config from "./configmodule.js";

//###########################################################
configurationOptions = {
  "set telegram-bot token": async function() {
    return (await setTelegramToken());
  },
  "set chat id": async function() {
    return (await setChatId());
  },
  "set max cycles": async function() {
    return (await setMaxCycles());
  },
  "check config": function() {
    return printConfig();
  },
  "back": function() {} // handled in loop
};

//###########################################################
done = false;

// local state for immediate feedback
localTgToken = config.tgToken;

localTgChatId = config.tgChatId;

localMaxCycles = config.maxCycles;

//###########################################################
export var configure = async function() {
  var choice;
  log("configure");
  done = false;
  while (!done) {
    choice = (await ui.retrieveChoice("Configuration:", Object.keys(configurationOptions)));
    if (choice === "back") {
      done = true;
    } else {
      await configurationOptions[choice]();
    }
  }
};

//###########################################################
printConfig = function() {
  log("printConfig");
  console.log(`tgToken:    ${localTgToken || '(not set)'}`);
  console.log(`tgChatId:   ${localTgChatId || '(not set)'}`);
  console.log(`maxCycles:  ${localMaxCycles}`);
};

setTelegramToken = async function() {
  var token;
  log("setTelegramToken");
  token = (await ui.retrieveSecret("Telegram Bot Token:"));
  await config.updateConfig({
    tgToken: token
  });
  localTgToken = token;
  console.log("Token updated.");
};

setChatId = async function() {
  var chatId;
  log("setChatId");
  chatId = (await ui.retrieveString("Telegram Chat ID:"));
  await config.updateConfig({
    tgChatId: chatId
  });
  localTgChatId = chatId;
  console.log("Chat ID updated.");
};

setMaxCycles = async function() {
  var input, num;
  log("setMaxCycles");
  input = (await ui.retrieveString(`Max Cycles (current: ${localMaxCycles}):`));
  num = parseInt(input, 10);
  if (isNaN(num)) {
    console.log("Invalid input. Please enter a number.");
    return;
  }
  await config.updateConfig({
    maxCycles: num
  });
  localMaxCycles = num;
  console.log("Max cycles updated.");
};
